spring:
  datasource:
    url: jdbc:mysql:///moneymonster?useSSL=false&serverTimezone=UTC
    username: root
    password: dragon4
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*